#### crowsnest.conf
#### This is a typical default config.
#### Also used as default in mainsail / MainsailOS
#### See:
#### https://github.com/mainsail-crew/crowsnest/blob/master/README.md
#### for details to configure to your needs.


#####################################################################
####                                                            #####
####      Information about ports and according URL's           #####
####                                                            #####
#####################################################################
####                                                            #####
####    Port 8080 equals /webcam/?action=[stream/snapshot]      #####
####    Port 8081 equals /webcam2/?action=[stream/snapshot]     #####
####    Port 8082 equals /webcam3/?action=[stream/snapshot]     #####
####    Port 8083 equals /webcam4/?action=[stream/snapshot]     #####
####                                                            #####
#####################################################################


[crowsnest]
log_path: ~/printer_data/logs/crowsnest.log
log_level: verbose                      #  Valid Options are quiet/verbose/debug
delete_log: false                       #  Deletes log on every restart, if set to true

[cam Logitech_C920_PRO]
mode: mjpg                              #  mjpg/rtsp
port: 8081                              #  Port
device: /dev/v4l/by-id/usb-046d_HD_Pro_Webcam_C920_6A89A69F-video-index0                     #  See Log for available ...
resolution: 1920x1080                   #  widthxheight format
max_fps: 15                             #  If Hardware Supports this it will be forced, ohterwise ignored/coerced.
#custom_flags:                          #  You can run the Stream Services with custom flags.
v4l2ctl: focus_auto=0,focus_absolute=0

[cam Nozzlecam]
mode: mjpg                              #  mjpg/rtsp
port: 8080                              #  Port
device: /dev/v4l/by-id/usb-Generic_USB2.0_PC_CAMERA-video-index0                     #  See Log for available ...
resolution: 640x480                     #  widthxheight format
max_fps: 15                             #  If Hardware Supports this it will be forced, ohterwise ignored/coerced.